"""Initial

Revision ID: 2cce1e1ee174
Revises: 
Create Date: 2024-11-03 19:35:45.224076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cce1e1ee174'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('complexity', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('input_data', sa.String(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('secret_answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task')),
    schema='public'
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    schema='public'
    )
    op.create_table('user_task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('solved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['public.task.id'], name=op.f('fk_user_task_task_id_task')),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], name=op.f('fk_user_task_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_task')),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_task', schema='public')
    op.drop_table('user', schema='public')
    op.drop_table('task', schema='public')
    # ### end Alembic commands ###
